version: 2.1

workflows:
  my-workflow:
    jobs:
      - build:
          context: cumulus-packages

jobs:
  build:
    docker:
      - image: circleci/node:12.18.0
    working_directory: ~/project
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install
          command: npm install npm@latest && npm install
      - run:
          name: Lint
          command: npm run lint
      - run:
          name: Test
          command: npm run test
      - run:
          name: Build
          command: docker build -t cumuluss/cumulus-ecs-task .
      - run:
          name: Deploy
          command: |
            if [[  "$CIRCLE_BRANCH" == 'master' ]]; then
              GITHUB_TOKEN=${GITHUB_TOKEN} ./bin/release.sh
              echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
            fi
